name: 1point3acre get credits with docker
on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

jobs:
  _1point3acres:
    runs-on: ubuntu-latest
    name: get credits
    steps:
    - name: run docker
      id: checkin
      uses: harryhare/1point3acres@main
      with:
        users: ${{ secrets.USERS }}
    - name: get the result
      run: echo "${{ steps.checkin.outputs.result }}"