name: 'dog bark every hour'

on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bark every minute
        run: echo "汪"
